databases:
  - name: budget_app
    databaseName: budget_app_37xj
    user: budget_app_37xj_user

services:
  - type: web
    name: ruby-recipe
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ruby-recipe
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
