default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ruby_recipe_app_development
  username: postgres
  password: jgrsfhhggff
  host: localhost
  port: 5432

test:
  <<: *default
  database: ruby_recipe_app_test
  username: postgres
  password: jgrsfhhggff
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  
